#!/bin/bash
# This script was auto-generated by the Tapis Jobs Service for the purpose
# of running a Tapis application.  The order of execution is as follows:
#
#   1. The batch scheduler options are passed to the scheduler, including any
#      user-specified, scheduler-managed environment variables.
#   2. The application container is run with container options, environment
#      variables and application parameters as supplied in the Tapis job,
#      application and system definitions.
# Slurm directives.
#SBATCH --account usc143
#SBATCH --job-name tapisjob.sh
#SBATCH --mem 16000
#SBATCH --nodes 1
#SBATCH --ntasks 1
#SBATCH --output '/expanse/lustre/projects/usc143/qwxdev/apps/expanse/rocky8.8/bbp/c73e4c7/slurm_out.log'
#SBATCH --partition debug
#SBATCH --time 30

/expanse/lustre/projects/usc143/qwxdev/apps/expanse/rocky8.8/bbp/c73e4c7/osp_run.sh

