name: bbp-ci

on:
  push:
    branches: [ dev ]

jobs:
  bbp-build-linux:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ 3.7 ]
    steps:
    - name: set BBP_DIR
      run: echo "BBP_BASE_DIR=$RUNNER_WORKSPACE/bbp" >> $GITHUB_ENV
    - name: checkout bbp dev
      uses: actions/checkout@v2
      with:
        ref: dev
    - name: build bbp
      run: ./.github/scripts/bbp-build-ci.sh
      shell: bash
    - name: test bbp
      run: ./.github/scripts/bbp-test-ci.sh
      shell: bash
