name: bbp-ci

on:
  push:
    branches: [ dev ]

jobs:
  bbp-build-linux:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ 3.7.6 ]
    steps:
    - name: set BBP_DIR
      run: echo "BBP_BASE_DIR=$RUNNER_WORKSPACE/bbp" >> $GITHUB_ENV
    - name: Setup Python
      uses: actions/setup-python@v3
      with:
        python-version: 3.7
    - name: configure Python
      run: |
      sudo apt-get update
      sudo apt-get install g++-8 -y
      sudo apt-get install gfortran-8 -y
      pip install numpy
      pip instlal scipy
      pip install matplotlib
      pip install pyproj
      pip install numba
      sudo apt-get install libfftw3-dev libfftw3-doc
#    - name: set up Python 3.7
#      uses: actions/setup-python@v3
#      with:
#        python-version: '3.7.6'
    - name: checkout bbp dev
      uses: actions/checkout@v2
      with:
        ref: dev
    - name: build bbp
      run: ./.github/scripts/bbp-build-ci.sh
      shell: bash
    - name: test bbp
      run: ./.github/scripts/bbp-test-ci.sh
      shell: bash
